import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowRight } from "lucide-react"

export default function StartupsPage() {
  return (
    <main className="flex flex-col min-h-screen">
      {/* Hero Section */}
      <section className="bg-[#1f273a] text-white py-16 md:py-24">
        <div className="container mx-auto px-4 md:px-6 text-center">
          <h1 className="text-3xl md:text-5xl font-bold mb-6">Startups Accelerator</h1>
          <p className="text-lg md:text-xl max-w-3xl mx-auto">
            The BSA is also a wonderful startups incubator. We incentivize students and collaborators to build as much
            value as they can.
          </p>
        </div>
      </section>

      {/* Startups Grid */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Startup 1 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  W3
                </div>
                <h3 className="text-xl font-bold">Digital agency for Web3 design and development</h3>
              </div>
              <p className="text-gray-700 mb-6">
                Get a website or DeFi webApp which suits your needs and goals, using top tier UI/UX and smart contracts
                integration.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 2 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  DL
                </div>
                <h3 className="text-xl font-bold">The derivatives layer for DeFi yield</h3>
              </div>
              <p className="text-gray-700 mb-6">
                Speculate on the evolution of the yield generated by different DeFi protocols. Hedge your risk on your
                passive revenue.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 3 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  F2P
                </div>
                <h3 className="text-xl font-bold">Free2Play Massive Multiplayer Game on Starknet</h3>
              </div>
              <p className="text-gray-700 mb-6">
                Join thousands of players in massively multiplayer events, compete to earn assets and use your wallet to
                see and manage your collection.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 4 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  HL
                </div>
                <h3 className="text-xl font-bold">Turn NFTs into financial assets</h3>
              </div>
              <p className="text-gray-700 mb-6">
                Honey Labs pioneers liquidity solutions for NFTs, and allows you to access DeFi through your NFTs.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 5 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  AM
                </div>
                <h3 className="text-xl font-bold">Automate the management of Convex (CVX) and Aura (AURA) positions</h3>
              </div>
              <p className="text-gray-700 mb-6">
                By depositing and minting WAR, users can stake into the system to earn revenue from protocol rewards and
                vote incentives.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 6 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  DF
                </div>
                <h3 className="text-xl font-bold">Get the best out of DeFi in one place</h3>
              </div>
              <p className="text-gray-700 mb-6">
                Swap any token from any chain, generate yield, leverage your assets and simply access the best
                protocols.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>

            {/* Startup 7 */}
            <div className="bg-gray-50 rounded-lg p-8 border border-gray-200">
              <div className="flex items-center mb-6">
                {/* Placeholder for logo */}
                <div className="bg-[#1f273a] text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mr-4">
                  CR
                </div>
                <h3 className="text-xl font-bold">Acquire cryptocurrencies anywhere with ease</h3>
              </div>
              <p className="text-gray-700 mb-6">
                With Crypties you can acquire crypto easily nearly anywhere with more than 800 points of sales in
                Switzerland.
              </p>
              <Button
                asChild
                variant="outline"
                className="flex items-center gap-2 border-[#1f273a] text-[#1f273a] hover:bg-[#1f273a] hover:text-white"
              >
                <Link href="#">
                  DISCOVER <ArrowRight size={16} />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Join the Accelerator CTA */}
      <section className="py-16 bg-gray-50 border-t border-gray-200">
        <div className="container mx-auto px-4 md:px-6 text-center">
          <h2 className="text-2xl md:text-4xl font-bold mb-6">Join Our Startup Accelerator</h2>
          <p className="text-lg mb-8 max-w-2xl mx-auto">
            Have a blockchain project or startup idea? Apply to join our accelerator program and get access to
            mentorship, resources, and networking opportunities.
          </p>
          <Button asChild size="lg" className="bg-[#1f273a] hover:bg-[#2a3349]">
            <Link href="/contact">Apply Now</Link>
          </Button>
        </div>
      </section>
    </main>
  )
}

