import { StartupType } from "../types";

export const startups: StartupType[] = [
  {
    img: "/startups/AAA Logotext White.webp",
    title: "Digital agency for Web3 design and development:",
    description:
      "Get a website or DeFi webApp which suits your needs and goals, using top tier UI/UX and smart contracts integration.",
    link: "https://ascentadastra.com",
  },
  {
    img: "/startups/spectra_logo.png",
    title: "The derivatives layer for DeFi yield:",
    description:
      "Speculate on the evolution of the yield generated by different DeFi protocols. Hedge your risk on your passive revenue.",
    link: "https://www.spectra.finance/",
  },
  {
    img: "/startups/metacube-logo.png",
    title: "Free2Play Massive Multiplayer Game on Starknet:",
    description:
      "Join thousands of players in massively multiplayer events, compete to earn assets and use your wallet to see and manage your collection",
    link: "https://metacube.games/",
  },
  {
    img: "/startups/abstract-horizon.png",
    title: "Learn everything about the Abstract ecosystem:",
    description:
      "Abstract Horizon is the leading media about the Abstract Chain, a layer 2 blockchain focused on consumer applications.",
    link: "https://abstracthorizon.xyz/",
  },
  {
    img: "/startups/HONEY.webp",
    title: "Turn NFTs into financial assets:",
    description:
      "Honey Labs pioneers liquidity solutions for NFTs, and allows you to access DeFi through your NFTs.",
    link: "https://y.at/%F0%9F%8D%AF%F0%9F%8D%AF%F0%9F%90%9D",
  },
  {
    img: "/startups/warlord-logo.png",
    title: "Automate the management of Convex (CVX) and Aura (AURA) positions:",
    description:
      "By depositing and minting WAR, users can stake into the system to earn revenue from protocol rewards and vote incentives.",
    link: "https://warlord.paladin.vote/",
  },
  {
    img: "/startups/OnDefy.webp",
    title: "Get the best out of DeFi in one place:",
    description:
      "Swap any token from any chain, generate yield, leverage your assets and simply access the best protocols.",
    link: "https://ondefy.com",
  },
  {
    img: "/startups/Crypties_white.webp",
    title: "The first NFT collection on Starknet:",
    description:
      "Join the Crypties community and be part of the first NFT collection on Starknet, with unique art and exclusive benefits.",
    link: "https://crypties.xyz",
  }
]; 